# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Inicio
    url: index/
    weight: 10
    hasChildren: true
  - parent: Inicio
    name: Problemática
    url: problematica/
    weight: 30
  - parent: Inicio
    name: Objetivos
    url: objetivos/
    weight: 20
  - parent: Inicio
    name: Impacto esperado
    url: impacto_esperado/
    weight: 10
  - parent: Inicio
    name: Financiación
    url: financiacion/
    weight: 10
  - name: Equipo
    url: /#equipo
    weight: 20
  - parent: Equipo
    name: ERTIS
    url: ertis/
    weight: 10
  - parent: Equipo
    name: CEHIUMA
    url: cehiuma/
    weight: 10
  - name: Sitios Piloto
    url: /#reto
    weight: 30
  - parent: Sitios Piloto
    name: Villanueva de Tapia
    url: villanueva_de_tapia/
    weight: 30
  - parent: Sitios Piloto
    name: Sierra de Yeguas
    url: sierra_de_yeguas/
    weight: 20
  - parent: Sitios Piloto
    name: Teba
    url: teba/
    weight: 10
  - parent: Sitios Piloto
    name: Cuevas del Becerro
    url: cuevas_del_becerro/
    weight: 10
  - name: Divulgación
    url: /#divulgacion
    weight: 30
  - parent: Divulgación
    name: Noticias
    url: noticias/
    weight: 20
  - parent: Divulgación
    name: Publicaciones
    url: publicaciones/
    weight: 10
  - parent: Divulgación
    name: Eventos
    url: eventos/
    weight: 10
